const customMapping: { [key: string]: string } = {
    php: "php",
    cs: "csharp",
    cpp: "cpp",
    cc: "cpp",
    cxx: "cpp",
    c: "c",
    h: "c",
    hpp: "cpp",
    kt: "kotlin",
    kts: "kotlin",
    rb: "ruby",
    rs: "rust",
    go: "go",
    swift: "swift",
    scala: "scala",
    sh: "shell",
    bash: "shell",
    yaml: "yaml",
    yml: "yaml",
    toml: "toml",
    sql: "sql",
    md: "markdown",
    json: "json",
    xml: "xml",
    dart: "dart",
    lua: "lua",
    r: "r",
}

export default customMapping